#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_985e2d6-false}" && return 0; sourced_985e2d6=true

#MISE description="Install Nu-shell scripts."

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
set -- _LIBDIR . "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

gen_cmd_script() {
  cat <<EOF
@ECHO OFF
set original_dir=%CD%
cd ${PROJECT_DIR}
call mise.cmd exec --cd %original_dir% github:nushell/nushell -- nu ${PROJECT_DIR}\\${1} %*
EOF
}

gen_sh_script() {
  cat <<EOF
#!/usr/bin/env sh
original_dir="\$PWD"
cd "$PROJECT_DIR"
./mise exec --cd "\$original_dir" github:nushell/nushell -- nu "${PROJECT_DIR}/$1" "\$@"
EOF
}

install() {
  cd "$PROJECT_DIR" || exit 1
  local bin_dir_path="$HOME"/nu-bin
  mkdir -p "$bin_dir_path"
  rm -fr "${bin_dir_path:?}"/*
  local file
  for file in *.nu
  do
    test -e "$file" || continue
    case "$file" in
      (_*) continue;;
    esac
    local name="${file%.nu}"
    if is_windows
    then
      gen_cmd_script "$file" >"$bin_dir_path"/"$name".cmd
    else
      gen_sh_script "$file" >"$bin_dir_path"/"$name"
      chmod +x "$bin_dir_path"/"$name"
    fi
  done
}

install "$@"
