#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_985e2d6-false}" && return 0; sourced_985e2d6=true

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
set -- _LIBDIR . "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

gen_caller_script() {
  cat <<EOF
#!/usr/bin/env sh
original_dir="\$PWD"
cd "$PROJECT_DIR"
./mise exec --cd "\$original_dir" github:nushell/nushell -- nu "$PROJECT_DIR/$1" "\$@"
EOF
}

install() {
  local nu_bin_dir_path="$HOME"/nu-bin
  mkdir -p "$nu_bin_dir_path"
  local nu_file
  for nu_file in *.nu
  do
    test -e "$nu_file" || continue
    case "$nu_file" in
      (_*) continue;;
    esac
    local nu_name="${nu_file%.nu}"
    gen_caller_script "$nu_file" >"$nu_bin_dir_path"/"$nu_name"
    if is_windows
    then
      cat ../task.cmd >"$nu_bin_dir_path"/"$nu_name".cmd
    fi
    chmod 755 "$nu_bin_dir_path"/"$nu_name"
  done
}

case "${0##*/}" in
  (install)
    set -o nounset -o errexit
    install "$@"
    ;;
esac
