#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_1b73bd7-false}" && return 0; sourced_1b73bd7=true

# Mise - Home | mise-en-place https://mise.jdx.dev/
mise_ver_e8ccfbb='2026.6.14'

should_exec_9bf84a8=false

mise() {
  local os
  local exe_ext=
  if test -r /System/Library/CoreServices/SystemVersion.plist
  then
    os=macos
  elif test -d c:/
  then
    os=windows
    exe_ext=.exe
  elif test -d /sys
  then
    os=linux
  else
    exit 1
  fi
  local cache_dir_path="${XDG_CACHE_HOME:-$HOME}"/.cache/mise
  mkdir -p "$cache_dir_path"
  local cmd_path="$cache_dir_path/mise-$mise_ver_e8ccfbb$exe_ext"
  if ! command -v "$cmd_path" >/dev/null 2>&1
  then
    local arch
    case "$(uname -m)" in
      (x86_64) arch=x64;;
      (arm64) arch=arm64;;
    esac
    local url="https://github.com/jdx/mise/releases/download/v$mise_ver_e8ccfbb/mise-v$mise_ver_e8ccfbb-$os-$arch$exe_ext"
    echo "Downloading $url" >&2
    curl --fail --location "$url" --output "$cmd_path" || exit 1
    chmod +x "$cmd_path"
  fi
  export MISE_ACTIVATE_AGGRESSIVE=true
  if "$should_exec_9bf84a8"
  then
    exec "$cmd_path" "$@"
  fi
  command "$cmd_path" "$@"
}

case "${0##*/}" in
  (mise|mise.sh)
    set -o nounset -o errexit
    should_exec_9bf84a8=true
    mise "$@"
    ;;
esac
