#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh

# Executes the shell script with the same name but with a `.sh` extension in the same directory.

set -o nounset -o errexit

export ARG0="$0"
export ARG0BASE="${0##*/}"
script_dir="${0%/*}"
if test "$script_dir" = "$0"
then
  script_file_path=.
else
  script_file_path="$script_dir"/"$ARG0BASE".sh
fi
for SH in /bin/dash /bin/ash /bin/bash
do
  # Avoid using Dash on Debian because it is built with --disable-lineno option.
  test "$SH" = /bin/dash && test -e /etc/debian_version && continue
  # Avoid using Bash on macOS because it is locked to version 3.* and buggy.
  test "$SH" = "/bin/bash" && test -e /System/Library/CoreServices/SystemVersion.plist && continue
  if test -x "$SH"
  then
    export SH
    exec "$SH" "$script_file_path" "$@"
  fi
done
echo "No appropriate shell found." >&2
exit 1
