#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
cd "$1" || exit 1; shift 2

task() {
  test $# = 0 && exec "$_APPDIR"/mise tasks

  local mise_env=
  OPTIND=1; while getopts _-:E: OPT
  do
    test "$OPT" = - && OPT="${OPTARG%%=*}" && OPTARG="${OPTARG#"$OPT"=}"
    case "$OPT" in
      (E|env) mise_env="$OPTARG";;
      (?) exit 1;;
      (*) echo "$0: illegal option -- $OPT" >&2; exit 1;;
    esac
  done
  shift $((OPTIND-1))

  set -- run "$@"
  if test -n "$mise_env"
  then
    set -- --env "$mise_env" "$@"
  fi
  exec "$_APPDIR"/mise "$@"
}

case "${0##*/}" in
  (task|task.sh)
    set -o nounset -o errexit
    task "$@"
    ;;
esac
