[vars]
# Releases · msys2/msys2-installer https://github.com/msys2/msys2-installer/releases
msys2_version = "2026-06-11"

[tools."http:msys2"]
os = ["windows"]
version = "{{ vars.msys2_version }}"
bin_path = "msys64/usr/bin"
# “version” cannot be filtered as tera template.
# Package: base - MSYS2 Packages https://packages.msys2.org/packages/base
url = 'https://github.com/msys2/msys2-installer/releases/download/{{ version }}/msys2-base-{{ arch(x64="x86_64") }}-{{ vars.msys2_version | replace(from="-", to="") }}.tar.zst'
platforms.windows-amd64 = { checksum = "sha256:ace898d250d7302a24259a0288d69354649365af9cc64c8bcc2f219bc1e28374" }
# Package: diffutils - MSYS2 Packages https://packages.msys2.org/packages/diffutils
postinstall = 'cd /d %MISE_TOOL_INSTALL_PATH%\msys64 & curl -fsSL -o - https://mirror.msys2.org/msys/x86_64/diffutils-3.12-1-x86_64.pkg.tar.zst | tar --zstd -xf -'
