# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_ab72cef-false}" && return 0; sourced_ab72cef=true

set -- "$PWD" "${0%/*}" "$@"; test -z "${_APPDIR-}" && { test "$2" = "$0" && _APPDIR=. || _APPDIR="$2"; cd "$_APPDIR" || exit 1; }
set -- _LIBDIR .lib "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

# The Haskell Tool Stack
task_stack() {
  stack "$@"
}

# Glasgow Haskell Compiler
task_ghc() {
  stack exec ghc "$@"
}

# Glasgow Haskell Compiler Interpreter
task_ghci() {
  stack exec ghci "$@"
}

gen_commands_hs() {
  local message="Code generated by task:build task. DO NOT EDIT."
  # Datasources - gomplate documentation https://docs.gomplate.ca/datasources/
  {
    printf "{'message':'%s','list':[" "$message"
    grep -El '^commandInfo = ' src/*.hs \
    | while read -r line
      do
        line="${line#*/}"
        line="${line%.hs}"
        printf "{'name':'%s'}," "$line"
      done
    printf "]}"
  } \
  | gomplate -d data=stdin:?type=application/json -f=src/Commands.hs.tmpl \
  > src/Commands.hs
}

# Build
#MISE tools={"gomplate"="5.0.0"}
task_build() {
  gen_commands_hs
  local name
  name="${1-"main-exe"}"
  stack build hsprj:"$name"
  local cmd_path
  cmd_path="$(stack exec which "$name")"
  if is_windows
  then
    # Fixme
    cmd_path="$(stack exec cygpath -- --windows "$cmd_path")"
  fi
  mkdir -p ./build/
  cp -a "$cmd_path" ./build/
  echo Copied the command to: ./build/"$(basename "$cmd_path")" >&2
}

gen_sh_script() { cat <<EOF
#!/usr/bin/env sh
exec "$PROJECT_DIR"/build/main-exe"$exe_ext" "$name" "\$@"
EOF
}

# Install
#MISE depends=["build"]
task_install() {
  push_dir "$PROJECT_DIR" || exit 1
  local bin_dir_path="$HOME"/hs-bin
  mkdir -p "$bin_dir_path"
  rm -fr "${bin_dir_path:?}"/*
  ./build/main-exe subcmds \
  | while read -r name _
    do
      gen_sh_script >"$bin_dir_path"/"$name"
      chmod +x "$bin_dir_path"/"$name"
      if is_windows
      then
        # Create Busybox ash shim.
        cat task.cmd >"$bin_dir_path"/"$name".cmd
      fi
    done
  pop_dir
}

# stack haddock --dependencies-only

case "${0##*/}" in
  (tasks-project.sh|tasks-project)
    set -o nounset -o errexit
    "$@"
    ;;
esac
