#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_ed7ed88-false}" && return 0; sourced_ed7ed88=true

#MISE description="Build stuff."
# #MISE depends=["tasks:expand"]

test "${_APPDIR+set}" = set || { cd "${0%/*}" || cd "${0%\\*}" || cd . || exit 1; _APPDIR="$PWD"; cd "$OLDPWD" || exit 1; } 2>/dev/null
if test "${1:+$1}" = _LIBDIR; then cd "$2" || exit 1; else cd "$_APPDIR" || exit 1; fi; set -- "$OLDPWD" "$@"
set -- _LIBDIR ../../.lib "$@"
. ../../.lib/utils.sh
. ../../.lib/embed-script.sh
shift 2
cd "$1" || exit 1; shift

: "${LSV_EMBED_TARGETS=}"

build() {
  local IFS="$ch_lf"
  # shellcheck disable=SC2086
  embed_minified $LSV_EMBED_TARGETS
}

case "${0##*/}" in
  (build)
    set -o nounset -o errexit
    build "$@"
    ;;
esac
