#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
_() { eval "\${_LOADED_$1-false}" || ! eval "_LOADED_$1=true"; }; _ TASKS_BUILD && return

#MISE description="Build stuff."

# shellcheck disable=SC3028,SC3054
if test "${BASH_VERSION+set}"; then cd "${BASH_SOURCE[0]%[/\\]*}" || cd .; elif test "${1-}" = SCRIPTDIR; then cd "$2" || exit; else cd "${0%[/\\]*}" || cd .; fi 2>/dev/null; set -- SCRIPTDIR ../../.lib "$OLDPWD" "$@"
. ../../.lib/utils.sh
. ../../.lib/embed-script.sh
. ../../.lib/embed-heredoc.sh
cd "$3" || exit; shift 3

: "${LSV_EMBED_SCRIPT_TARGETS=}"
: "${LSV_EMBED_HEREDOC_TARGETS=}"

build() {
  local IFS="$CH_LF"
  # shellcheck disable=SC2086
  embed_minified $LSV_EMBED_SCRIPT_TARGETS
  # shellcheck disable=SC2086
  embed_heredoc $LSV_EMBED_HEREDOC_TARGETS
}

_() { case "${0##*[/\\]}" in ("$1"|"$1".*) ;; (*) false;; esac; }; if _ build
then
  set -o nounset -o errexit
  build "$@"
fi
