#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
_() { eval "\${_LOADED_$1-false}" || ! eval "_LOADED_$1=true"; }; _ TASKS_BUILD && return

#MISE description="Build stuff."

test "${_APPDIR+set}" = set || { cd "${0%[/\\]*}" 2>/dev/null || cd .; _APPDIR="$PWD"; cd "$OLDPWD" || exit; }
case "${1-}" in (_LIBDIR) cd "$2" || exit;; (*) cd "$_APPDIR" || exit;; esac; set -- "$OLDPWD" "$@";
set -- _LIBDIR ../../.lib "$@"
. ../../.lib/utils.sh
. ../../.lib/embed-script.sh
. ../../.lib/embed-heredoc.sh
shift 2
cd "$1" || exit; shift

: "${LSV_EMBED_SCRIPT_TARGETS=}"
: "${LSV_EMBED_HEREDOC_TARGETS=}"

build() {
  local IFS="$ch_lf"
  # shellcheck disable=SC2086
  embed_minified $LSV_EMBED_SCRIPT_TARGETS
  # shellcheck disable=SC2086
  embed_heredoc $LSV_EMBED_HEREDOC_TARGETS
}

_() { case "${0##*[/\\]}" in ("$1"|"$1".*) ;; (*) false;; esac; }; if _ build
then
  set -o nounset -o errexit
  build "$@"
fi
