#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh

#MISE description="[names...] Run tests. If no test names are provided, all tests are run."

test "${_APPDIR+set}" = set || { cd "${0%[/\\]*}" 2>/dev/null || cd .; _APPDIR="$PWD"; cd "$OLDPWD" || exit; }
case "${1-}" in (_LIBDIR) cd "$2" || exit;; (*) cd "$_APPDIR" || exit;; esac; set -- "$OLDPWD" "$@";
set -- _LIBDIR ../../.lib "$@"
. ../../.lib/utils.sh
shift 2
cd "$1" || exit; shift

"$PROJECT_DIR"/.lib-test/run-tests.sh "$@"
