#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_cc46c5c-false}" && return 0; sourced_cc46c5c=true

#MISE description="[names...] Run tests. If no test names are provided, all tests are run."

test "${_APPDIR+set}" = set || { cd "${0%[/\\]*}" || cd . || exit 1; _APPDIR="$PWD"; cd "$OLDPWD" || exit 1; } 2>/dev/null
case "${1:+$1}" in (_LIBDIR) cd "$2" || exit 1;; (*) cd "$_APPDIR" || exit 1;; esac; set -- "$OLDPWD" "$@";
set -- _LIBDIR ./.lib "$@"
. ./.lib/utils.sh
shift 2
cd "$1" || exit 1; shift

test_47fd512() {
  push_dir "$INITIAL_DIR"/.lib-test || exit 1
  ./run-tests "$@"
  pop_dir || exit 1
}

_() { test "${0##*/}" = "$1" -o "${0##*\\}" = "$1" -o "${0##*/}" = "$1.sh" -o "${0##*\\}" = "$1.sh"; }; if _ test
then
  set -o nounset -o errexit
  test_47fd512 "$@"
fi
