-- Code generated by task:build task. DO NOT EDIT.

module Commands (registerAll) where

import Command

import qualified Greet
import qualified Hello

registerAll :: [Command.Info] -> [Command.Info]
registerAll cmds =
  Greet.commandInfo:
  Hello.commandInfo:
  cmds
