-- Code generated by task:build task. DO NOT EDIT.

module Commands (registerAll) where

import Command
import Greet
import Hello
import Httpd

registerAll :: [Command.Info] -> [Command.Info]
registerAll cmds =
  Greet.commandInfo:
  Hello.commandInfo:
  Httpd.commandInfo:
  cmds
