min_version = "2026.6.11"

[settings]
activate_aggressive = true
# Print output as it comes in to utilize Gum. // Settings | mise-en-place https://mise.jdx.dev/configuration/settings.html
task_output = "interleave"

[env]
MISE_PID = "{{ mise_pid }}"

[tools]
"node" = "24"
"python" = "3.14"
"jq" = "1.8.1"
"yj" = "5.1.0"
"yq" = "4.52.4"
"gum" = "0.17.0"
