min_version = "2026.6.11"

[settings]
activate_aggressive = true
# Print output as it comes in to utilize Gum. // Settings | mise-en-place https://mise.jdx.dev/configuration/settings.html
task_output = "interleave"

[env]
MISE_PID = "{{ mise_pid }}"

[vars]
# Releases · msys2/msys2-installer https://github.com/msys2/msys2-installer/releases
MSYS2_VERSION = "2026-06-11"
MSYS2_AMD64_SUM = "sha256:ace898d250d7302a24259a0288d69354649365af9cc64c8bcc2f219bc1e28374"

[tools]
"node" = "24"
"python" = "3.14"
"jq" = "1.8.1"
"yj" = "5.1.0"
"yq" = "4.52.4"
"gum" = "0.17.0"

# Releases · msys2/msys2-installer https://github.com/msys2/msys2-installer/releases
[tools."http:msys2"]
os = ["windows"]
version = "{{ vars.MSYS2_VERSION }}"
bin_path = "msys64/usr/bin"
# “version” cannot be filtered as tera template.
url = 'https://github.com/msys2/msys2-installer/releases/download/{{ version }}/msys2-base-{{ arch(x64="x86_64") }}-{{ vars.MSYS2_VERSION | replace(from="-", to="") }}.tar.zst'
checksum_url = 'https://github.com/msys2/msys2-installer/releases/download/{{ version }}/msys2-base-{{ arch(x64="x86_64") }}-{{ vars.MSYS2_VERSION | replace(from="-", to="") }}.tar.zst'
platforms.windows-amd64 = { checksum = "{{ vars.MSYS2_AMD64_SUM }}" }
