min_version = "2026.7.18"

[settings]
activate_aggressive = true
# Print output as it comes in to utilize Gum. // Settings | mise-en-place https://mise.jdx.dev/configuration/settings.html
task.output = "interleave"

[env]
APP_ENV = "development"
MISE_PID = "{{ mise_pid }}"
MISE_BIN = "{{ mise_bin }}"
LSV_EMBED_SCRIPT_TARGETS = """
{{ config_root }}/.lib/json2sh.sh
{{ config_root }}/.mise/tasks/tasks/expand.sh
"""
LSV_EMBED_HEREDOC_TARGETS = """
{{ config_root }}/.mise/tasks/bootstrap/generate.sh
{{ config_root }}/.lib/shpp.sh
"""
LSV_SHPP_TARGETS = """
{{ config_root }}/bin/**/*.sh
{{ config_root }}/bin/**/*.bash
{{ config_root }}/.lib/**/*.sh
{{ config_root }}/.lib/**/*.bash
{{ config_root }}/.lib-test/*.sh
{{ config_root }}/.lib-test/*.bash
{{ config_root }}/.mise/**/*.sh
{{ config_root }}/.mise/**/*.bash
{{ config_root }}/conf/.mise/**/*.sh
{{ config_root }}/conf/.mise/**/*.bash
{{ config_root }}/go/.mise/**/*.bash
{{ config_root }}/py/.mise/**/*.sh
{{ config_root }}/py/.mise/**/*.sh
"""
# _.path = ["{{ config_root }}/.mise/preferred-sh"]
HEREDOC = { default = """
foo \
bar \
baz \
""" }

[tools]
# "node" = "24"
"python" = "3.14"
"jq" = "1.8.1"
"yj" = "5.1.0"
"yq" = "4.52.4"
"gum" = "0.17.0"
"watchexec" = "2.5.1"
