# vim: set filetype=bash tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=bash
_() { case "${_ids-}" in (*$1*) ;; (*) _ids="$1,${_ids-}"; false;; esac; }; _ 5a19848 && return 0

# Rewrite the TypeScript code generated by sqlc.
rewrite_sqlcgen_ts() {
  perl -pi \
    -e 'if (m#^.*cloudflare/workers-types/2022-11-30.*$#) { $_ = "" };' \
    -e 's#^([[:blank:]]*[_[:alnum:]]+)(: .* \| null;)$#$1?$2#;' \
    -e 's#^(.*\.bind\()([^.][^)]*)(\).*)$#$1 . join(", ", map { "typeof $_ === \"undefined\"? null: $_" } split(/,\s*/, $2)) . $3#e;' \
    "$@"
}
