#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_5e327a4-false}" && return 0; sourced_5e327a4=true

set -- "$PWD" "${0%/*}" "$@"; test -z "${_APPDIR-}" && { test "$2" = "$0" && _APPDIR=. || _APPDIR="$2"; cd "$_APPDIR" || exit 1; }
set -- _LIBDIR .lib "$@"
shift 2
cd "$1" || exit 1; shift 2

_default() {
  echo "Function \"_default\" is not implemented yet."
}

case "${0##*/}" in
  (_default)
    set -o nounset -o errexit
    _default "$@"
    ;;
esac
