#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_9a4b0a2-false}" && return 0; sourced_9a4b0a2=true

set -- "$PWD" "${0%/*}" "$@"; test -z "${_APPDIR-}" && { test "$2" = "$0" && _APPDIR=. || _APPDIR="$2"; cd "$_APPDIR" || exit 1; }
set -- _LIBDIR .lib "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

build1() {
  cat source >dest
  echo "Built." >&2
}

case "${0##*/}" in
  (build1)
    set -o nounset -o errexit
    build1 "$@"
    ;;
esac
