#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_ed7ed88-false}" && return 0; sourced_ed7ed88=true

#MISE description="Build stuff."
#MISE depends=["versions:sync", "task:route"]

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
set -- _LIBDIR .lib "$@"
. ./.lib/utils.lib.sh
. ./.lib/embed-script.lib.sh
shift 2
cd "$1" || exit 1; shift 2

build() {
  embed_minified \
    "$TASK_PROJECT_DIR"/lib-sh/json2sh.lib.sh \
    "$TASK_PROJECT_DIR"/mise-tasks/task/route \
    #nop
}

case "${0##*/}" in
  (build)
    set -o nounset -o errexit
    build "$@"
    ;;
esac
