#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_79a3b07-false}" && return 0; sourced_79a3b07=true

set -- "$PWD" "${0%/*}" "$@"; test -z "${_APPDIR-}" && { test "$2" = "$0" && _APPDIR=. || _APPDIR="$2"; cd "$_APPDIR" || exit 1; }
set -- _LIBDIR .lib "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

main1() {
  register_child_cleanup

  watchexec -f source -- mise run build1 &

  while :
  do
    echo Main >&2
    sleep 1
  done
}

case "${0##*/}" in
  (main1)
    set -o nounset -o errexit
    main1 "$@"
    ;;
esac
