#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_cc46c5c-false}" && return 0; sourced_cc46c5c=true

#MISE description="[names...] Run tests. If no test names are provided, all tests are run."

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
set -- _LIBDIR .lib "$@"
. .lib/utils.lib.sh
. .lib/test.lib.sh
shift 2
cd "$1" || exit 1; shift 2

test_47fd512() {
  cd "$PROJECT_DIR/.lib-test" || exit 1
  run_tests "$@"
}

case "${0##*/}" in
  (test|test.sh)
    set -o nounset -o errexit
    test_47fd512 "$@"
    ;;
esac
