#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_4a3c429-false}" && return 0; sourced_4a3c429=true

#MISE description="Install shell scripts."

set -- "$PWD" "${0%/*}" "$@"; if test -z "${_APPDIR-}"; then _APPDIR=.; if test "$2" != "$0"; then _APPDIR="$2"; fi; cd "$_APPDIR" || exit 1; fi
set -- _LIBDIR .lib "$@"
. ./.lib/utils.lib.sh
shift 2
cd "$1" || exit 1; shift 2

gen_sh_script() { cat <<EOF
#!/usr/bin/env sh
exec "\${SH:-$SH}" "$PROJECT_DIR"/"$file" "\$@"
EOF
}

# Install shell scripts.
install() {
  push_dir "$PROJECT_DIR" || exit 1
  local bin_dir_path="$HOME"/sh-bin
  mkdir -p "$bin_dir_path"
  if test "${executed_thru_t_bb789ec+set}" = set
  then
    echo "In a Windows environment, $bin_dir_path/t.sh is not replaced because it is locked. Run ./task.cmd instead." >&2
    return 1
  fi
  rm -fr "${bin_dir_path:?}"/*
  local file
  for file in *.sh
  do
    test -e "$file" || continue
    case "$file" in
      (_*) continue;;
    esac
    local name="${file%.sh}"
    gen_sh_script >"$bin_dir_path"/"$name"
    chmod +x "$bin_dir_path"/"$name"
    if is_windows
    then
      # Create Busybox ash shim.
      cat task.cmd >"$bin_dir_path"/"$name".cmd
    fi
  done
  pop_dir
}

case "${0##*/}" in
  (install)
    set -o nounset -o errexit
    install "$@"
    ;;
esac
