#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_f72a086-false}" && return 0; sourced_f72a086=true

set -- "$PWD" "${0%/*}" "$@"; test -z "${_APPDIR-}" && { test "$2" = "$0" && _APPDIR=. || _APPDIR="$2"; cd "$_APPDIR" || exit 1; }
set -- _LIBDIR .lib "$@"
shift 2
cd "$1" || exit 1; shift 2

beep() {
  if test -d "c:/" -o -d "/c/"
  then
    # pwsh -c "[console]::beep(1000,300)" &
    rundll32 user32.dll,MessageBeep &
  elif test -r /System/Library/CoreServices/SystemVersion.plist
  then
    osascript -e 'beep' &
  fi
}

set -o nounset -o errexit
beep "$@"
