run-name: >-
  ${{
    github.event_name == 'schedule' && 'Scheduled Test 🗓️' ||
    github.event_name == 'workflow_dispatch' && 'Manual Trigger 🚀' ||
    github.event.head_commit.message
  }}
name: Tests
on:
  push:
    branches:
      - main
  # “The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.”
  # “In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. ”
  #
  # — Events that trigger workflows - GitHub Docs https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  #
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  # │ │ │ │ │
  # * * * * *
  #
  schedule:
    # Runs every Saturday at 00:00 UTC
    - cron: '0 0 * * 6'
  workflow_dispatch:
env:
  VERBOSE: true
jobs:
  test-unixy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      # actions/checkout: Action for checking out a repo https://github.com/actions/checkout
      - uses: actions/checkout@v7
      # jdx/mise-action https://github.com/jdx/mise-action
      - uses: jdx/mise-action@v4
      - name: Uname
        run: uname -a
      - name: Environment Variables
        run: env
      - name: Bash Version
        run: bash --version
      - name: Run Dash Tests
        run: dash ./.lib-test/run-tests.sh
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: mise run test
      - name: Run Full Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: mise run test --full
      - name: Mise bootstrap
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: ./mise version
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Enable Symlinks
        run: git config --global core.symlinks true
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: System Info
        run: systeminfo
      - name: Environment Variables
        run: set
        shell: cmd
      - name: BusyBox Ash Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: .\task.cmd ./.lib-test/run-tests.sh
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: mise run test
      - name: Run Full Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: mise run test --full
      - name: Mise bootstrap
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: .\mise.cmd version
