name: Tests
on:
  push:
    branches:
      - main
jobs:
  test-unixy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uname
        run: uname -a
      - name: Environment Variables
        run: env
      - name: Processes
        run: ps -aww -o pid,ppid,command
      - name: Run Test
        run: ./task --verbose test
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Enable Symlinks
        run: git config --global core.symlinks true
      - uses: actions/checkout@v4
      - name: System Info
        run: systeminfo
      - name: Environment Variables
        run: set
        shell: cmd
      - name: Load BusyBox
        run: .\task.cmd nop
      - name: Run Test
        run: .\task.cmd --verbose test
