run-name: >-
  ${{
    github.event_name == 'schedule' && 'Scheduled Test 🗓️' ||
    github.event_name == 'workflow_dispatch' && 'Manual Trigger 🚀' ||
    github.event.head_commit.message
  }}
name: Tests
on:
  push:
    branches:
      - main
  # “The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.”
  # “In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. ”
  #
  # — Events that trigger workflows - GitHub Docs https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:
env:
  VERBOSE: true
jobs:
  test-unixy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uname
        run: uname -a
      - name: Environment Variables
        run: env
      - name: Bash Version
        run: bash --version
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: ./task test
      - name: Run All Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: ./task test --full
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Enable Symlinks
        run: git config --global core.symlinks true
      - uses: actions/checkout@v4
      - name: System Info
        run: systeminfo
      - name: Environment Variables
        run: set
        shell: cmd
      - name: Cache BusyBox
        # actions/cache: Cache dependencies and build outputs in GitHub Actions https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          # “Please note that Windows environment variables (like %LocalAppData%) will NOT be expanded by this action. Instead, prefer using ~ in your paths which will expand to the HOME directory.”
          path: ~\.cache\busybox
          key: busybox-${{ runner.os }}-${{ hashFiles('task.cmd') }}
          restore-keys: |
            busybox-${{ runner.os }}-
      - name: Load BusyBox
        run: .\task.cmd nop
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: .\task.cmd test
      - name: Run All Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: .\task.cmd test --full
