run-name: >-
  ${{
    github.event_name == 'schedule' && 'Scheduled Test 🗓️' ||
    github.event_name == 'workflow_dispatch' && 'Manual Trigger 🚀' ||
    github.event.head_commit.message
  }}
name: Tests
on:
  push:
    branches:
      - main
  # “The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.”
  # “In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. ”
  #
  # — Events that trigger workflows - GitHub Docs https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:
env:
  VERBOSE: true
jobs:
  test-unixy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - name: Uname
        run: uname -a
      - name: Environment Variables
        run: env
      - name: Bash Version
        run: bash --version
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: mise run test
      - name: Run All Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: mise run test --full
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Enable Symlinks
        run: git config --global core.symlinks true
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - name: System Info
        run: systeminfo
      - name: Environment Variables
        run: set
        shell: cmd
      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        run: mise run test
      - name: Run All Tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' && github.event.schedule == '0 0 * * 6' }}
        run: mise run test --full
