min_version = '2026.2.7'

[settings]
# Print output as it comes in to utilize Gum. // Settings | mise-en-place https://mise.jdx.dev/configuration/settings.html
task_output = "interleave"

[env]
MISE_PID = "{{mise_pid}}"

[tools]
"gum" = "0.17.0"
"watchexec" = "2.3.3"
"ghcup" = "0.1.50.2"
"stack" = "3.9.3"

[tools."github:msys2/msys2-installer"]
os = ["windows"]
version = "2026-06-11"
matching_regex = ".*zst.*"
bin_path = "msys64/usr/bin"

# powershell | mise versions https://mise-versions.jdx.dev/tools/powershell
[tools."powershell"]
# os = ["linux", "macos"]
version = "7"
